# Site settings
title: Dynamics of Astronomy
email: antognini@astronomy.ohio-state.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joe-antognini.github.io" # the base hostname & protocol for your site
github_username:  joe-antognini

# Build settings
markdown: kramdown
